// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpserver

import (
	"github.com/google/wire"
	"github.com/kangyueyue/short-url/internal/httpserver/hello"
	"github.com/kangyueyue/short-url/internal/httpserver/redirect"
	"github.com/kangyueyue/short-url/internal/httpserver/short_url"
	"github.com/kangyueyue/short-url/internal/infrastructure/store"
)

// Injectors from wire.go:

// InitialHttpServer 初始化服务
func InitialHttpServer(store2 *store.Store) *Server {
	helloSvr := hello.NewHelloSvr()
	shortUrlSvr := short_url.NewShortUrlSvr(store2)
	redirectSvr := redirect.NewRedirectSvr(store2)
	server := NewServer(helloSvr, shortUrlSvr, redirectSvr)
	return server
}

// wire.go:

var SvrSet = wire.NewSet(hello.NewHelloSvr, short_url.NewShortUrlSvr, redirect.NewRedirectSvr)
