// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "get": {
                "description": "这是一个Hello World接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "Hello 示例接口",
                "responses": {
                    "200": {
                        "description": "Hello World",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/short_url/del": {
            "delete": {
                "description": "根据短链标识和客户端ID删除对应的短链",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "删除短链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.DelVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                        }
                    }
                }
            }
        },
        "/short_url/get": {
            "post": {
                "description": "根据短链接获取原始长链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "获取长链接",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.GetVO"
                        }
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回长链接信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.PShortUrlData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                        }
                    }
                }
            }
        },
        "/short_url/list": {
            "get": {
                "description": "根据client_id获取对应的短链列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "获取短链列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "短链列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PShortUrlData"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                        }
                    }
                }
            }
        },
        "/short_url/set": {
            "post": {
                "description": "批量创建短链接，将长链接转换为短链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "创建短链接",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.SetVo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回短链接信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.PShortUrlData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_kangyueyue_short-url_internal_http.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kangyueyue_short-url_internal_http.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.PShortUrlData": {
            "type": "object",
            "properties": {
                "clientId": {
                    "description": "用户id",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "expireAt": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "longUrl": {
                    "description": "长链-使用utf8mb4_bin字符集，区分大小写",
                    "type": "string"
                },
                "shortUrl": {
                    "description": "短链-使用utf8mb4_bin字符集，区分大小写",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "vo.DelVo": {
            "type": "object",
            "required": [
                "shortUrl"
            ],
            "properties": {
                "isDisk": {
                    "description": "是否删除磁盘文件",
                    "type": "boolean"
                },
                "shortUrl": {
                    "type": "string"
                }
            }
        },
        "vo.GetVO": {
            "type": "object",
            "required": [
                "shortUrl"
            ],
            "properties": {
                "shortUrl": {
                    "type": "string"
                }
            }
        },
        "vo.SetVo": {
            "type": "object",
            "required": [
                "clientId",
                "longUrls"
            ],
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "longUrls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
