info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: 这是一个Hello World接口
      produces:
      - application/json
      responses:
        "200":
          description: Hello World
          schema:
            type: string
      summary: Hello 示例接口
      tags:
      - 测试
swagger: "2.0"
